name: continuous-integration-action
description: Action for continuous integration
inputs:
  SONAR_PROJECT_KEY:
    description: Sonarqube project key
    required: true
  SONAR_HOST_URL:
    description: Sonarqube host url
    required: true
  SONARQUBE_TOKEN:
    description: Sonarqube token
    required: true
  MIN_COVERAGE_VALUE:
    description: Minimum coverage value
    required: false
    default: 40
    type: integer
  MIN_BUGS_VALUE:
    description: Minimum bugs value
    required: false
    default: 0
    type: integer
  MIN_HOTSPOTS_VALUE:
    description: Minimum hotspots value
    required: false
    default: 0
    type: integer
  MIN_EFFORT_VALUE:
    description: Minimum effort value
    required: false
    default: 60
    type: integer

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
      shell: bash
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Build and analyze
      run: ./gradlew build sonar --info
      env:
        SONAR_TOKEN: ${{ inputs.SONARQUBE_TOKEN }}
      shell: bash
