name: Template

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Execute Continuous Integration Action
      uses: PruebaSonarCloud/PruebaCIZAndroid/.github/actions/continuous-integration-action@main
      with:
        SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONARQUBE_TOKEN : ${{ secrets.SONARQUBE_TOKEN }}
        



    
    
    
    
          
    
          
    
    
    
    

      

